# Generated by Django 6.0.7 on 2026-08-01 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name="So'z")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Taqiqlangan so'z",
                'verbose_name_plural': "Taqiqlangan so'zlar",
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Qisqa tavsif')),
                ('part_number', models.PositiveSmallIntegerField(default=1, verbose_name='Qism raqami')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/', verbose_name='PDF fayl')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='Muqova')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['order', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Unvon / lavozim')),
                ('icon', models.CharField(default='⚔', max_length=10, verbose_name='Emoji')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('race', models.CharField(blank=True, max_length=50, verbose_name='Xalq / irq')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Rasm')),
                ('is_featured', models.BooleanField(default=True, verbose_name="Bosh sahifada ko'rsatish")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Qahramon',
                'verbose_name_plural': 'Qahramonlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ism')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='Matn')),
                ('message_type', models.CharField(choices=[('text', 'Matn'), ('image', 'Rasm'), ('sticker', 'Stiker')], default='text', max_length=10, verbose_name='Turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='Rasm')),
                ('sticker', models.CharField(blank=True, max_length=10, verbose_name='Stiker')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Yashirilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
            ],
            options={
                'verbose_name': 'Chat xabari',
                'verbose_name_plural': 'Chat xabarlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL uchun (masalan: gondor)', unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('color', models.CharField(default='#c9a34e', help_text='HEX rang, masalan #c9a34e', max_length=20)),
                ('icon', models.CharField(default='👑', max_length=10, verbose_name='Emoji ikonka')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Qisqa shior')),
                ('symbol', models.CharField(blank=True, max_length=100, verbose_name='Ramz')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('traits', models.TextField(blank=True, help_text='Har bir xususiyatni yangi qatorda yozing', verbose_name='Xususiyatlar')),
                ('ruler_name', models.CharField(blank=True, max_length=100, verbose_name='Hukmdor nomi')),
                ('ruler_title', models.CharField(blank=True, max_length=100, verbose_name='Hukmdor unvoni')),
                ('ruler_image', models.ImageField(blank=True, null=True, upload_to='factions/', verbose_name='Hukmdor rasmi')),
                ('castle_name', models.CharField(blank=True, max_length=100, verbose_name="Qal'a nomi")),
                ('castle_image', models.ImageField(blank=True, null=True, upload_to='factions/', verbose_name="Qal'a rasmi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fraksiya',
                'verbose_name_plural': 'Fraksiyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Tavsif')),
                ('icon', models.CharField(default='📜', max_length=10, verbose_name='Ikonka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Forum bo'limi",
                'verbose_name_plural': "Forum bo'limlari",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Hudud')),
                ('location_type', models.CharField(choices=[('region', 'Hudud'), ('city', 'Shahar'), ('fortress', "Qal'a"), ('forest', "O'rmon"), ('mountain', "Tog'"), ('other', 'Boshqa')], default='region', max_length=20, verbose_name='Turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('population', models.CharField(blank=True, max_length=100, verbose_name='Aholi')),
                ('landmarks', models.TextField(blank=True, help_text='Diqqatga sazovor joylar (har birini yangi qatorda)', verbose_name='Diqqatga sazovor joylar')),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Rasm')),
                ('pos_x', models.FloatField(default=50, verbose_name='X pozitsiya (%)')),
                ('pos_y', models.FloatField(default=50, verbose_name='Y pozitsiya (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Xarita joyi',
                'verbose_name_plural': 'Xarita joylari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Uzuklar Hukmdori', max_length=200, verbose_name='Sayt nomi')),
                ('site_tagline', models.CharField(blank=True, default="O'rta Yer haqidagi afsona", max_length=300, verbose_name='Shior')),
                ('hero_text', models.TextField(blank=True, verbose_name='Bosh sahifa matni')),
                ('footer_text', models.TextField(blank=True, verbose_name='Footer matni')),
                ('chat_enabled', models.BooleanField(default=True, verbose_name='Muhokama yoqilgan')),
                ('gandalf_enabled', models.BooleanField(default=True, verbose_name='Gandalf yoqilgan')),
                ('registration_enabled', models.BooleanField(default=True, verbose_name="Ro'yxatdan o'tish yoqilgan")),
                ('game_download_enabled', models.BooleanField(default=True, verbose_name="O'yin yuklash yoqilgan")),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Texnik ishlar rejimi')),
                ('maintenance_message', models.TextField(blank=True, default='Sayt vaqtincha texnik ishlar tufayli yopiq. Tez orada qaytamiz!', verbose_name='Texnik ishlar xabari')),
                ('max_chat_message_length', models.PositiveIntegerField(default=500, verbose_name='Max xabar uzunligi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('body', models.TextField(max_length=5000, verbose_name='Matn')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Qadalgan')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Yopilgan')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Yashirilgan')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='myapp.forumcategory', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=5000, verbose_name='Matn')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Yashirilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('favorite_race', models.CharField(blank=True, choices=[('elf', 'Elflar'), ('human', 'Odamlar'), ('dwarf', 'Gnomlar'), ('hobbit', 'Xobbitlar'), ('ent', 'Entlar'), ('ainur', 'Aynurlar'), ('orc', 'Orklar'), ('uruk_hai', 'Uruk-xaylar'), ('troll', 'Trollar'), ('dragon', 'Ajdaholar'), ('warg', 'Varglar')], max_length=20)),
                ('faction', models.CharField(blank=True, choices=[('gondor', 'Gondor'), ('rohan', 'Rohan'), ('rivendell', 'Rivendell'), ('lothlorien', 'Lothlorien'), ('woodland_realm', 'Woodland Realm'), ('erebor', 'Erebor'), ('mordor', 'Mordor'), ('isengard', 'Isengard'), ('goblin', 'Goblinlar')], max_length=30)),
                ('is_banned', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('ban_reason', models.CharField(blank=True, max_length=255, verbose_name='Blok sababi')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('reputation', models.IntegerField(default=0, verbose_name="Obro'")),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Moderator')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
    ]
