# Generated by Django 6.0.7 on 2026-07-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name="So'z")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Taqiqlangan so'z",
                'verbose_name_plural': "Taqiqlangan so'zlar",
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Qisqa tavsif')),
                ('part_number', models.PositiveSmallIntegerField(default=1, verbose_name='Qism raqami')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/', verbose_name='PDF fayl')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='Muqova')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['order', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Unvon / lavozim')),
                ('icon', models.CharField(default='⚔', max_length=10, verbose_name='Emoji')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('race', models.CharField(blank=True, max_length=50, verbose_name='Xalq / irq')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Rasm')),
                ('is_featured', models.BooleanField(default=True, verbose_name="Bosh sahifada ko'rsatish")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Qahramon',
                'verbose_name_plural': 'Qahramonlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL uchun (masalan: gondor)', unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('color', models.CharField(default='#c9a34e', help_text='HEX rang, masalan #c9a34e', max_length=20)),
                ('icon', models.CharField(default='👑', max_length=10, verbose_name='Emoji ikonka')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Qisqa shior')),
                ('symbol', models.CharField(blank=True, max_length=100, verbose_name='Ramz')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('traits', models.TextField(blank=True, help_text='Har bir xususiyatni yangi qatorda yozing', verbose_name='Xususiyatlar')),
                ('ruler_name', models.CharField(blank=True, max_length=100, verbose_name='Hukmdor nomi')),
                ('ruler_title', models.CharField(blank=True, max_length=100, verbose_name='Hukmdor unvoni')),
                ('ruler_image', models.ImageField(blank=True, null=True, upload_to='factions/', verbose_name='Hukmdor rasmi')),
                ('castle_name', models.CharField(blank=True, max_length=100, verbose_name="Qal'a nomi")),
                ('castle_image', models.ImageField(blank=True, null=True, upload_to='factions/', verbose_name="Qal'a rasmi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fraksiya',
                'verbose_name_plural': 'Fraksiyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Hudud')),
                ('location_type', models.CharField(choices=[('region', 'Hudud'), ('city', 'Shahar'), ('fortress', "Qal'a"), ('forest', "O'rmon"), ('mountain', "Tog'"), ('other', 'Boshqa')], default='region', max_length=20, verbose_name='Turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('population', models.CharField(blank=True, max_length=100, verbose_name='Aholi')),
                ('landmarks', models.TextField(blank=True, help_text='Diqqatga sazovor joylar (har birini yangi qatorda)', verbose_name='Diqqatga sazovor joylar')),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Rasm')),
                ('pos_x', models.FloatField(default=50, verbose_name='X pozitsiya (%)')),
                ('pos_y', models.FloatField(default=50, verbose_name='Y pozitsiya (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Xarita joyi',
                'verbose_name_plural': 'Xarita joylari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Uzuklar Hukmdori', max_length=200, verbose_name='Sayt nomi')),
                ('site_tagline', models.CharField(blank=True, default="O'rta Yer haqidagi afsona", max_length=300, verbose_name='Shior')),
                ('hero_text', models.TextField(blank=True, verbose_name='Bosh sahifa matni')),
                ('footer_text', models.TextField(blank=True, verbose_name='Footer matni')),
                ('chat_enabled', models.BooleanField(default=True, verbose_name='Muhokama yoqilgan')),
                ('gandalf_enabled', models.BooleanField(default=True, verbose_name='Gandalf yoqilgan')),
                ('registration_enabled', models.BooleanField(default=True, verbose_name="Ro'yxatdan o'tish yoqilgan")),
                ('game_download_enabled', models.BooleanField(default=True, verbose_name="O'yin yuklash yoqilgan")),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Texnik ishlar rejimi')),
                ('maintenance_message', models.TextField(blank=True, default='Sayt vaqtincha texnik ishlar tufayli yopiq. Tez orada qaytamiz!', verbose_name='Texnik ishlar xabari')),
                ('max_chat_message_length', models.PositiveIntegerField(default=500, verbose_name='Max xabar uzunligi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat xabari', 'verbose_name_plural': 'Chat xabarlari'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Foydalanuvchi profili', 'verbose_name_plural': 'Foydalanuvchi profillari'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Yashirilgan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Blok sababi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Bloklangan'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Matn'), ('image', 'Rasm'), ('sticker', 'Stiker')], default='text', max_length=10, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sticker',
            field=models.CharField(blank=True, max_length=10, verbose_name='Stiker'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='Matn'),
        ),
    ]
