# Generated by Django 6.0.7 on 2026-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_seed_forum_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Faqat admin panelda ko'rinadi (masalan: 'Yangi yil aksiyasi').", max_length=150, verbose_name='Ichki nom')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Banner rasmi')),
                ('url', models.URLField(blank=True, help_text="Bosilganda foydalanuvchi shu manzilga o'tadi. Bo'sh qoldirilsa, banner bosilmaydigan bo'ladi.", max_length=500, verbose_name='Havola (URL)')),
                ('placement', models.CharField(choices=[('header', 'Sarlavha osti (barcha sahifalar, yuqorida)'), ('index_middle', "Bosh sahifa — bo'limlar orasida"), ('footer', 'Footer tepasi (barcha sahifalar, pastda)')], default='header', max_length=20, verbose_name='Joylashuvi')),
                ('open_new_tab', models.BooleanField(default=True, verbose_name='Yangi oynada ochilsin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('click_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Bosilganlar soni')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name="Ko'rsatilganlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
                'ordering': ['placement', 'order', '-created_at'],
            },
        ),
    ]
