# Generated by Django 6.0.7 on 2026-08-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='banner_style',
            field=models.CharField(choices=[('1', '1 — Klassik uchli'), ('2', '2 — Ayri dumli (lasttochka)'), ('3', "3 — To'lqinli chekka"), ('4', '4 — Bayroqcha (qiya uchli)'), ('5', '5 — Qalqon shakli'), ('6', '6 — Lenta (tasma, ikki uchli)'), ('7', '7 — Gotik uchli')], default='1', help_text="Fraksiya bannerlari uslubidagi 7 xil shakldan biri — faqat 'Yon banner' uchun.", max_length=2, verbose_name='Banner shakli'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='side',
            field=models.CharField(choices=[('left', 'Chap tomon'), ('right', "O'ng tomon")], default='right', help_text="Faqat 'Yon banner' joylashuvi uchun ishlaydi — chap yoki o'ng chekkada chiqadi.", max_length=5, verbose_name='Tomoni'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('side', "Yon banner (chap yoki o'ng, doim ko'rinadi)"), ('index_middle', "Bosh sahifa — bo'limlar orasida"), ('footer', 'Footer tepasi (barcha sahifalar, pastda)')], default='side', max_length=20, verbose_name='Joylashuvi'),
        ),
    ]
